# Generated by Django 5.0.7 on 2024-08-03 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudBNUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_memo', models.IntegerField(blank=True, null=True)),
                ('correo_solicitante', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombre_solicitante', models.CharField(max_length=255)),
                ('numero_ingreso', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('depto_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnup.departamento')),
                ('funcionario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnup.funcionario')),
                ('tipo_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnup.tiporecepcion')),
            ],
        ),
    ]
