# Generated by Django 3.2.15 on 2024-08-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudbnup',
            name='archivo_adjunto_ingreso',
            field=models.FileField(blank=True, null=True, upload_to='archivos_adjuntos/'),
        ),
    ]
