# Generated by Django 3.2.15 on 2024-08-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0002_solicitudbnup_archivo_adjunto_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudbnup',
            name='archivo_adjunto_salida',
            field=models.FileField(blank=True, null=True, upload_to='archivos_adjuntos_salida/'),
        ),
        migrations.AddField(
            model_name='solicitudbnup',
            name='numero_salida',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
