# Generated by Django 3.2.15 on 2024-09-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0003_auto_20240826_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudbnup',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
