# Generated by Django 3.2.15 on 2024-10-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0004_solicitudbnup_fecha_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudbnup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
