# Generated by Django 3.2.15 on 2024-10-07 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0005_solicitudbnup_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaBNUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_salida', models.IntegerField()),
                ('fecha_salida', models.DateField()),
                ('archivo_adjunto_salida', models.FileField(blank=True, null=True, upload_to='archivos_adjuntos_salida/')),
                ('solicitud_bnup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='bnup.solicitudbnup')),
            ],
        ),
    ]
