# Generated by Django 3.2.15 on 2024-10-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0006_salidabnup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudbnup',
            name='archivo_adjunto_salida',
        ),
        migrations.RemoveField(
            model_name='solicitudbnup',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='solicitudbnup',
            name='numero_salida',
        ),
    ]
