# Generated by Django 3.2.15 on 2025-01-13 19:14

from django.db import migrations, models
import django.db.models.deletion


def create_default_tipo_solicitud(apps, schema_editor):
    TipoSolicitud = apps.get_model('bnup', 'TipoSolicitud')
    # Verificar si ya existe el registro para evitar duplicados
    if not TipoSolicitud.objects.filter(id=13012025).exists():
        TipoSolicitud.objects.create(id=13012025, tipo='Tipo de Solicitud Predeterminado')


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0007_auto_20241007_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RunPython(create_default_tipo_solicitud, migrations.RunPython.noop),
        migrations.AddField(
            model_name='solicitudbnup',
            name='fecha_egreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudbnup',
            name='tipo_solicitud',
            field=models.ForeignKey(default=13012025, on_delete=django.db.models.deletion.CASCADE, to='bnup.tiposolicitud'),
            preserve_default=False,
        ),
    ]
