# Generated by Django 3.2.15 on 2025-01-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0009_rename_models_and_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salidasolicitud',
            old_name='solicitud_bnup',
            new_name='ingreso_solicitud',
        ),
        migrations.RemoveField(
            model_name='ingresosolicitud',
            name='nombre_solicitante',
        ),
    ]
