# Generated by Django 3.2.15 on 2025-01-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0010_auto_20250115_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresosolicitud',
            name='funcionarios_asignados',
            field=models.ManyToManyField(related_name='ingresos', to='bnup.Funcionario'),
        ),
    ]
