# Generated by Django 3.2.15 on 2025-01-27 13:35

from django.db import migrations

def copy_funcionarios(apps, schema_editor):
    IngresoSOLICITUD = apps.get_model('bnup', 'IngresoSOLICITUD')
    for solicitud in IngresoSOLICITUD.objects.all():
        if solicitud.funcionario_asignado:
            solicitud.funcionarios_asignados.add(solicitud.funcionario_asignado)

class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0011_ingresosolicitud_funcionarios_asignados'),
    ]

    operations = [
        migrations.RunPython(copy_funcionarios),
    ]
