# Generated by Django 3.2.15 on 2025-01-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0012_migrate_funcionarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresosolicitud',
            name='funcionario_asignado',
        ),
    ]
