# Generated by Django 3.2.15 on 2025-02-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0013_remove_ingresosolicitud_funcionario_asignado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingresosolicitud',
            old_name='fecha_salida_solicitante',
            new_name='fecha_solicitud',
        ),
    ]
