# Generated by Django 3.2.15 on 2025-03-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0014_rename_fecha_salida_solicitante_ingresosolicitud_fecha_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidasolicitud',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salidasolicitud',
            name='funcionarios',
            field=models.ManyToManyField(blank=True, related_name='salidas', to='bnup.Funcionario'),
        ),
        migrations.AddField(
            model_name='salidasolicitud',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
