# Generated by Django 3.2.15 on 2025-07-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0015_auto_20250306_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgresoAU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_egreso', models.IntegerField(unique=True, verbose_name='Número de Egreso')),
                ('fecha_egreso', models.DateField(verbose_name='Fecha de Egreso')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='egresos_adjuntos/', verbose_name='Archivo Adjunto')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_recibidos', to='bnup.departamento', verbose_name='Destinatario')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresos_au', to='bnup.funcionario', verbose_name='Funcionario responsable')),
            ],
            options={
                'verbose_name': 'Egreso AU',
                'verbose_name_plural': 'Egresos AU',
                'ordering': ['-fecha_egreso', 'numero_egreso'],
            },
        ),
    ]
