# Generated by Django 3.2.15 on 2025-08-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0016_egresoau'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egresoau',
            options={'ordering': ['-numero_egreso'], 'verbose_name': 'Egreso AU', 'verbose_name_plural': 'Egresos AU'},
        ),
        migrations.RemoveField(
            model_name='egresoau',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='egresoau',
            name='funcionarios',
            field=models.ManyToManyField(related_name='egresos_au', to='bnup.Funcionario', verbose_name='Funcionarios responsables'),
        ),
    ]
