# Generated by Django 3.2.15 on 2025-08-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0017_auto_20250801_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresoau',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
