# Generated by Django 3.2.15 on 2025-08-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0018_egresoau_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresoau',
            name='archivo_respuesta',
            field=models.FileField(blank=True, null=True, upload_to='egresos_respuestas/', verbose_name='Archivo Respuesta'),
        ),
    ]
