# Generated by Django 3.2.15 on 2025-08-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0019_egresoau_archivo_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresoau',
            name='numero_egreso',
            field=models.IntegerField(verbose_name='Número de Egreso'),
        ),
        migrations.AddConstraint(
            model_name='egresoau',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('numero_egreso',), name='uniq_numero_egreso_activo'),
        ),
    ]
