# Generated by Django 3.2.15 on 2025-09-23 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bnup', '0020_auto_20250825_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario Django vinculado a este funcionario (fuente de email).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionario_bnup', to=settings.AUTH_USER_MODEL),
        ),
    ]
