# Generated by Django 3.2.15 on 2025-11-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0022_enable_unaccent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('incluye_todos', models.BooleanField(default=False, help_text='Si está activo, esta sección incluirá automáticamente a todos los funcionarios.')),
                ('funcionarios', models.ManyToManyField(blank=True, help_text="Sólo se utiliza cuando 'incluye_todos' está desactivado.", related_name='secciones', to='bnup.Funcionario')),
            ],
            options={
                'verbose_name': 'Sección de funcionarios',
                'verbose_name_plural': 'Secciones de funcionarios',
            },
        ),
    ]
