# Generated by Django 3.2.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnup', '0023_seccionfuncionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresosolicitud',
            name='fecha_maxima_respuesta',
            field=models.DateField(
                blank=True,
                help_text='Solo se usa cuando tipo de solicitud es Transparencia o Transparencia Activa.',
                null=True
            ),
        ),
    ]
