# Generated by Django 3.2.15 on 2024-11-08 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cerro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('departamento', models.CharField(blank=True, max_length=10, null=True)),
                ('cerro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patente_alcohol.cerro')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudPatenteAlcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_avaluo', models.CharField(max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='patente_alcohol/ingresos/')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patente_alcohol.solicitante')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patente_alcohol.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo_adjunto_salida', models.FileField(blank=True, null=True, upload_to='patente_alcohol/salidas/')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patente_alcohol.solicitudpatentealcohol')),
            ],
        ),
    ]
