# Generated by Django 3.2.15 on 2024-11-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patente_alcohol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudpatentealcohol',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='salida',
            name='numero_salida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitudpatentealcohol',
            name='numero_ingreso',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='solicitud',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='patente_alcohol.solicitudpatentealcohol'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salida', to='patente_alcohol.solicitudpatentealcohol'),
        ),
    ]
