# Generated by Django 3.2.15 on 2024-12-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patente_alcohol', '0002_auto_20241108_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='archivo_adjunto_salida',
            field=models.FileField(blank=True, null=True, upload_to='salidas_adjuntos/'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='salida',
            name='numero_salida',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
